
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 22:04:03 COT 2015
//----------------------------------------------------

package compi;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELSE = 20;
  public static final int OP_BINARIO = 15;
  public static final int IGUAL = 13;
  public static final int THEN = 19;
  public static final int WHILE = 21;
  public static final int PAR_CER = 8;
  public static final int PAR_AB = 7;
  public static final int END = 4;
  public static final int COR_CER = 12;
  public static final int DOSPUN = 6;
  public static final int IF = 18;
  public static final int ID = 3;
  public static final int OP_COMP = 16;
  public static final int TIPO = 2;
  public static final int DO = 22;
  public static final int OP_UNARIO = 14;
  public static final int COMA = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COR_AB = 11;
  public static final int ENTERO = 17;
  public static final int LLAV_CER = 10;
  public static final int LLAV_AB = 9;
}

